# Generated by Django 2.2.1 on 2019-06-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='country',
            field=models.IntegerField(choices=[(1, 'Azerbaijan')], default=1),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
