# Generated by Django 2.2.1 on 2019-06-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0002_auto_20190605_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['country', 'county']},
        ),
    ]
