# Generated by Django 2.2.1 on 2019-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0003_auto_20190605_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
