# Generated by Django 2.2.1 on 2019-09-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
