# Generated by Django 2.2.1 on 2019-09-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0002_auto_20190901_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
