"""
Django settings for blood_bank_project project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '22c)vi$*%c-bu!vx&9ni&=_llea7nmwopvib%l46+a33ytyu5$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
HEROKU = False

ALLOWED_HOSTS = [
    "*"
]

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/'


# Application definition

INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django_celery_results',
    'allauth',
    'phone_field',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',
    'django_seed',
    'donor_app',
    'region_app',
    'auth_app',
    'homepage',
    'messages_extends',
    'faq',
    'contact',
    'snowpenguin.django.recaptcha2',
    'seo_app'

]

MESSAGE_STORAGE = 'messages_extends.storages.FallbackStorage'

# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_RESULT_BACKEND = 'redis://h:p7cb639d8320e9a6cf74f4f64e70dc71027ed8b4dbc5be6150681d522ee6808fe@ec2-63-35-249-65.eu-west-1.compute.amazonaws.com:21479'
# CELERY_BROKER_URL = CELERY_RESULT_BACKEND
CELERY_BROKER_URL = 'amqp://xilaset_user:Lappin555@localhost:5672//'
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# CELERY_BACKED_URL = 'redis://localhost:6379'

CRISPY_TEMPLATE_PACK = '4'

SITE_ID = 1

ACCOUNT_ACTIVATION_DAYS = 7
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_VERIFICATION = "none"

CRISPY_TEMPLATE_PACK = 'bootstrap3'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'middlewares.check_user_account.CheckUserAccount',
    'middlewares.SEO.SEOMiddleware',
    
]

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'blood_bank_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blood_bank_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


if HEROKU:
    # postgres://pbryzacbyqwbcj:ff2cdcd727978f5b17c53ee00f46dce030bef0aab4e422dbd92670f61b76c77d@ec2-54-75-230-253.eu-west-1.compute.amazonaws.com:5432/d7u88243ae0b8m
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'd7u88243ae0b8m',
            'USER': 'pbryzacbyqwbcj',
            'PASSWORD': 'ff2cdcd727978f5b17c53ee00f46dce030bef0aab4e422dbd92670f61b76c77d',
            'PORT': 5432,
            'HOST': 'ec2-54-75-230-253.eu-west-1.compute.amazonaws.com'
        }
    }
    
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'blood_donor',
            'USER': 'root',
            'PASSWORD': '123456',
            'PORT': 3307,
            'HOST': '127.0.0.1'
        }
    }
else:
    # postgres://pbryzacbyqwbcj:ff2cdcd727978f5b17c53ee00f46dce030bef0aab4e422dbd92670f61b76c77d@ec2-54-75-230-253.eu-west-1.compute.amazonaws.com:5432/d7u88243ae0b8m
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'ddlgikb5deh120',
            'USER': 'hllgszowclnrba',
            'PASSWORD': 'f26b8ab553cfd4767216dbc7be7702fcad1b0115a6347e871faab86174d7ed4e',
            'PORT': 5432,
            'HOST': 'localhost'
        }
    }



# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGES = (
    ('az', 'Azərbaycan dili'),
)

LANGUAGE_CODE = 'az'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


STATIC_ROOT = os.path.join(BASE_DIR, 'collectedstatic')


EMAIL_DEBUG = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'xilaset'
EMAIL_HOST_PASSWORD = 'x1l@$et2019'
DEFAULT_FROM_EMAIL = 'Elşad Ağayev <xilaset@gmail.com>'
SERVER_EMAIL = 'Elşad Ağayev <xilaset@gmail.com>'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'



RECAPTCHA_PRIVATE_KEY = '6Ldr97QUAAAAAOmW_W57MfNxPr0gHJH9sM7SiPUC'
RECAPTCHA_PUBLIC_KEY = '6Ldr97QUAAAAAGt0E5Vj3GpAqCIbzhFtpFy_wN9e'


DONATION_EXPIRE_TIME = 15552000 # 6 months
DONORS_PER_PAGE = 50
