# Generated by Django 2.2.1 on 2019-08-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor_app', '0013_donor_is_contact_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255)),
                ('contact_type', models.IntegerField(choices=[(1, 'Phone'), (2, 'Email'), (3, 'Facebook')])),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor_app.Donor')),
            ],
        ),
    ]
