# Generated by Django 2.2.1 on 2019-06-05 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('region_app', '0003_auto_20190605_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Field')),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender')),
                ('blood_group', models.IntegerField(choices=[(1, '+1'), (2, '-1'), (3, '+2'), (4, '-2'), (5, '+3'), (6, '-3'), (7, '+4'), (8, '-4')], verbose_name='Blood group')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='region_app.County', verbose_name='County')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
            },
        ),
    ]
