# Generated by Django 2.2.1 on 2019-06-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_price_per_100gramm',
            field=models.FloatField(default=0, verbose_name='Price per 100 gramm'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Last Name'),
        ),
    ]
