# Generated by Django 2.2.1 on 2019-06-05 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0002_auto_20190605_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.IntegerField(choices=[(1, '+A'), (2, '-A'), (3, '+B'), (4, '-B'), (5, '+O'), (6, '-O'), (7, '+AB'), (8, '-AB')], verbose_name='Blood group'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
