# Generated by Django 2.2.1 on 2019-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0005_auto_20190605_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
