# Generated by Django 2.2.1 on 2019-06-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0007_auto_20190605_1713'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='donor',
            index_together={('first_name', 'last_name', 'phone')},
        ),
    ]
