# Generated by Django 2.2.1 on 2019-06-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0008_auto_20190605_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Close account'),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='Account is private'),
        ),
    ]
