# Generated by Django 2.2.1 on 2019-06-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0009_auto_20190610_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='is_private',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Account is private'),
        ),
    ]
