# Generated by Django 2.2.1 on 2019-06-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0010_auto_20190610_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_private',
        ),
    ]
