# Generated by Django 2.2.1 on 2019-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0012_auto_20190610_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_contact_private',
            field=models.BooleanField(default=False, verbose_name='Contact is private'),
        ),
    ]
