# Generated by Django 2.2.1 on 2019-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0014_remove_donor_blood_price_per_100gramm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
    ]
